blueprint:
  name: Motion-activated Lights and Switches with Timeout
  description: >-
    Turn on specified lights and/or switches when motion is detected by one or more sensors.
    The devices will turn off after a specified delay once all sensors are clear.
    If motion is detected again during the delay, the turn-off timer resets.
  domain: automation
  input:
    motion_entity:
      name: Motion/Presence Sensor(s)
      description: The sensor(s) that will trigger the automation. Handles multiple sensors.
      selector:
        entity:
          domain: [binary_sensor, person, device_tracker]
          multiple: true
    target_light:
      name: Target Lights
      description: The light(s) to turn on when motion is detected.
      selector:
        target:
          entity:
            domain: light
    light_brightness:
      name: Light Brightness
      description: Brightness level for the lights (1-100%).
      default: 100
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          unit_of_measurement: "%"
    target_switch:
      name: Target Switches (Optional)
      description: The switch(es) to turn on when motion is detected.
      default: {}
      selector:
        target:
          entity:
            domain: switch
    wait_time:
      name: Timeout Delay
      description: Time in seconds to wait after all motion stops before turning off devices.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_entity

action:
  - variables:
      motion_detected: >-
        {{ expand(!input motion_entity) | selectattr('state', 'in', ['on', 'home']) | list | count > 0 }}

  - choose:
      - conditions: "{{ motion_detected }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_pct: !input light_brightness
          - if: "{{ (expand(!input target_switch) | list | count) > 0 }}"
            then:
              - service: switch.turn_on
                target: !input target_switch

      - conditions: "{{ not motion_detected }}"
        sequence:
          - delay:
              seconds: !input wait_time
          - service: light.turn_off
            target: !input target_light
          - if: "{{ (expand(!input target_switch) | list | count) > 0 }}"
            then:
              - service: switch.turn_off
                target: !input target_switch
