blueprint:
  name: Motion and Presence Activated Lights
  description: Turns on specified lights and/or switches when motion or presence is detected. The devices turn off after a configurable delay once all sensors report no activity. An optional toggle can be used to disable the automation.
  domain: automation
  input:
    motion_entity:
      name: Motion/Presence Sensor(s)
      description: The sensor(s) that will trigger the automation. Select one or more.
      selector:
        entity:
          multiple: true
          domain: binary_sensor
          device_class:
            - motion
            - presence
    light_target:
      name: Lights
      description: The light(s) to turn on when motion is detected.
      selector:
        target:
          entity:
            domain: light
    light_brightness:
      name: Light Brightness
      description: The brightness level (1-100) for the lights.
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
      default: 100
    switch_target:
      name: Switches (Optional)
      description: The switch(es) to turn on when motion is detected.
      selector:
        target:
          entity:
            domain: switch
      default: {}
    no_motion_wait:
      name: Turn-off Delay
      description: Time to wait after all motion has stopped before turning off the devices.
      selector:
        time:
      default: "00:05:00"
    disable_switch:
      name: Disable Switch (Optional)
      description: An optional input_boolean helper. If this switch is 'on', the automation will not run.
      selector:
        entity:
          domain: input_boolean
      default:

mode: restart

trigger:
  - platform: state
    entity_id: !input motion_entity
    to: 'on'
    from: 'off'

condition:
  - condition: template
    value_template: "{{ '!input disable_switch' == '' or is_state('!input disable_switch', 'off') }}"

action:
  - service: light.turn_on
    target: !input light_target
    data:
      brightness_pct: !input light_brightness
  - if:
      - "{{ !input switch_target != {} }}"
    then:
      - service: switch.turn_on
        target: !input switch_target
  - wait_template: "{{ expand(!input motion_entity) | map(attribute='state') | select('eq', 'on') | list | count == 0 }}"
  - delay: !input no_motion_wait
  - service: light.turn_off
    target: !input light_target
  - if:
      - "{{ !input switch_target != {} }}"
    then:
      - service: switch.turn_off
        target: !input switch_target
